/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "shibrpc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
shibrpc_ping_2(int *argp, int *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, shibrpc_ping,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
shibrpc_new_session_2(shibrpc_new_session_args_2 *argp, shibrpc_new_session_ret_2 *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, shibrpc_new_session,
		(xdrproc_t) xdr_shibrpc_new_session_args_2, (caddr_t) argp,
		(xdrproc_t) xdr_shibrpc_new_session_ret_2, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
shibrpc_get_session_2(shibrpc_get_session_args_2 *argp, shibrpc_get_session_ret_2 *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, shibrpc_get_session,
		(xdrproc_t) xdr_shibrpc_get_session_args_2, (caddr_t) argp,
		(xdrproc_t) xdr_shibrpc_get_session_ret_2, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
shibrpc_statemgr_2(shibrpc_statemgr_args_2 *argp, shibrpc_statemgr_ret_2 *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, shibrpc_statemgr,
		(xdrproc_t) xdr_shibrpc_statemgr_args_2, (caddr_t) argp,
		(xdrproc_t) xdr_shibrpc_statemgr_ret_2, (caddr_t) clnt_res,
		TIMEOUT));
}
