/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "shibrpc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
shibrpc_call_3(shibrpc_args_3 *argp, shibrpc_ret_3 *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, shibrpc_call,
		(xdrproc_t) xdr_shibrpc_args_3, (caddr_t) argp,
		(xdrproc_t) xdr_shibrpc_ret_3, (caddr_t) clnt_res,
		TIMEOUT));
}
