/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SHIBRPC_H_RPCGEN
#define _SHIBRPC_H_RPCGEN

#include <rpc/rpc.h>

#ifdef HAVE_PTHREAD
# include <pthread.h>
#endif

#ifdef __cplusplus
extern "C" {
#endif


struct shibrpc_args_3 {
	char *xml;
};
typedef struct shibrpc_args_3 shibrpc_args_3;

struct shibrpc_ret_3 {
	char *xml;
};
typedef struct shibrpc_ret_3 shibrpc_ret_3;

#define SHIBRPC_PROG 123456
#define SHIBRPC_VERS_3 3

#if defined(__STDC__) || defined(__cplusplus)
#define shibrpc_call 3
extern  enum clnt_stat shibrpc_call_3(shibrpc_args_3 *, shibrpc_ret_3 *, CLIENT *);
extern  bool_t shibrpc_call_3_svc(shibrpc_args_3 *, shibrpc_ret_3 *, struct svc_req *);
extern int shibrpc_prog_3_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define shibrpc_call 3
extern  enum clnt_stat shibrpc_call_3();
extern  bool_t shibrpc_call_3_svc();
extern int shibrpc_prog_3_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_shibrpc_args_3 (XDR *, shibrpc_args_3*);
extern  bool_t xdr_shibrpc_ret_3 (XDR *, shibrpc_ret_3*);

#else /* K&R C */
extern bool_t xdr_shibrpc_args_3 ();
extern bool_t xdr_shibrpc_ret_3 ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SHIBRPC_H_RPCGEN */
