/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "shibrpc.h"

/* sometimes xdr_enum_t is not defined properly */
#ifndef xdr_enum_t
#define xdr_enum_t xdr_enum
#endif

bool_t
xdr_ShibRpcStatus (XDR *xdrs, ShibRpcStatus *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ShibRpcHttpCookie_1 (XDR *xdrs, ShibRpcHttpCookie_1 *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->cookie, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->client_addr, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ShibRpcAttrReq_1 (XDR *xdrs, ShibRpcAttrReq_1 *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->req, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ShibRpcAttrRep_1 (XDR *xdrs, ShibRpcAttrRep_1 *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->rep, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_shibrpc_session_is_valid_args_1 (XDR *xdrs, shibrpc_session_is_valid_args_1 *objp)
{
	register int32_t *buf;

	 if (!xdr_ShibRpcHttpCookie_1 (xdrs, &objp->cookie))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->checkIPAddress))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->lifetime))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->timeout))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_shibrpc_session_is_valid_ret_1 (XDR *xdrs, shibrpc_session_is_valid_ret_1 *objp)
{
	register int32_t *buf;

	 if (!xdr_ShibRpcStatus (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->error_msg, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_shibrpc_new_session_args_1 (XDR *xdrs, shibrpc_new_session_args_1 *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->shire_location, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->saml_post, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->client_addr, ~0))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->checkIPAddress))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_shibrpc_new_session_ret_1 (XDR *xdrs, shibrpc_new_session_ret_1 *objp)
{
	register int32_t *buf;

	 if (!xdr_ShibRpcStatus (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->error_msg, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->cookie, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_shibrpc_get_attrs_args_1 (XDR *xdrs, shibrpc_get_attrs_args_1 *objp)
{
	register int32_t *buf;

	 if (!xdr_ShibRpcHttpCookie_1 (xdrs, &objp->cookie))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->checkIPAddress))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->url, ~0))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->attr_reqs.attr_reqs_val, (u_int *) &objp->attr_reqs.attr_reqs_len, ~0,
		sizeof (ShibRpcAttrReq_1), (xdrproc_t) xdr_ShibRpcAttrReq_1))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_shibrpc_get_attrs_ret_1 (XDR *xdrs, shibrpc_get_attrs_ret_1 *objp)
{
	register int32_t *buf;

	 if (!xdr_ShibRpcStatus (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->error_msg, ~0))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->attr_reps.attr_reps_val, (u_int *) &objp->attr_reps.attr_reps_len, ~0,
		sizeof (ShibRpcAttrRep_1), (xdrproc_t) xdr_ShibRpcAttrRep_1))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->assertion, ~0))
		 return FALSE;
	return TRUE;
}
