/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "shibrpc.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>

#ifdef WIN32
# include <winsock.h>
#else
# include <sys/socket.h>
# include <netinet/in.h>
#endif

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

void
shibrpc_prog_3(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		shibrpc_args_3 shibrpc_call_3_arg;
	} argument;
	union {
		shibrpc_ret_3 shibrpc_call_3_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case shibrpc_call:
		_xdr_argument = (xdrproc_t) xdr_shibrpc_args_3;
		_xdr_result = (xdrproc_t) xdr_shibrpc_ret_3;
		local = (bool_t (*) (char *, void *,  struct svc_req *))shibrpc_call_3_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!shibrpc_prog_3_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}
