/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SHIBRPC_H_RPCGEN
#define _SHIBRPC_H_RPCGEN

#include <rpc/rpc.h>

#ifdef HAVE_PTHREAD
# include <pthread.h>
#endif

#ifdef __cplusplus
extern "C" {
#endif


enum ShibRpcStatus {
	SHIBRPC_OK = 0,
	SHIBRPC_UNKNOWN_ERROR = 1,
	SHIBRPC_INTERNAL_ERROR = 2,
	SHIBRPC_XML_EXCEPTION = 3,
	SHIBRPC_SAX_EXCEPTION = 4,
	SHIBRPC_SAML_EXCEPTION = 5,
	SHIBRPC_NO_SESSION = 10,
	SHIBRPC_SESSION_EXPIRED = 11,
	SHIBRPC_IPADDR_MISMATCH = 12,
	SHIBRPC_IPADDR_MISSING = 20,
	SHIBRPC_RESPONSE_MISSING = 21,
	SHIBRPC_ASSERTION_REPLAYED = 22,
};
typedef enum ShibRpcStatus ShibRpcStatus;

struct ShibRpcErr {
	char *error;
	char *provider;
	char *url;
	char *contact;
	char *email;
};
typedef struct ShibRpcErr ShibRpcErr;

struct ShibRpcError {
	ShibRpcStatus status;
	union {
		ShibRpcErr e;
	} ShibRpcError_u;
};
typedef struct ShibRpcError ShibRpcError;

struct ShibRpcXML {
	char *xml_string;
};
typedef struct ShibRpcXML ShibRpcXML;

struct shibrpc_new_session_args_2 {
	char *application_id;
	char *packet;
	char *recipient;
	char *client_addr;
	bool_t checkIPAddress;
};
typedef struct shibrpc_new_session_args_2 shibrpc_new_session_args_2;

struct shibrpc_new_session_ret_2 {
	ShibRpcError status;
	char *target;
	char *cookie;
};
typedef struct shibrpc_new_session_ret_2 shibrpc_new_session_ret_2;

struct shibrpc_get_session_args_2 {
	char *application_id;
	char *cookie;
	char *client_addr;
	bool_t checkIPAddress;
	long lifetime;
	long timeout;
};
typedef struct shibrpc_get_session_args_2 shibrpc_get_session_args_2;

struct shibrpc_get_session_ret_2 {
	ShibRpcError status;
	ShibRpcXML auth_statement;
	struct {
		u_int assertions_len;
		ShibRpcXML *assertions_val;
	} assertions;
};
typedef struct shibrpc_get_session_ret_2 shibrpc_get_session_ret_2;

#define SHIBRPC_PROG 123456
#define SHIBRPC_VERS_2 2

#if defined(__STDC__) || defined(__cplusplus)
#define shibrpc_ping 0
extern  enum clnt_stat shibrpc_ping_2(int *, int *, CLIENT *);
extern  bool_t shibrpc_ping_2_svc(int *, int *, struct svc_req *);
#define shibrpc_new_session 1
extern  enum clnt_stat shibrpc_new_session_2(shibrpc_new_session_args_2 *, shibrpc_new_session_ret_2 *, CLIENT *);
extern  bool_t shibrpc_new_session_2_svc(shibrpc_new_session_args_2 *, shibrpc_new_session_ret_2 *, struct svc_req *);
#define shibrpc_get_session 2
extern  enum clnt_stat shibrpc_get_session_2(shibrpc_get_session_args_2 *, shibrpc_get_session_ret_2 *, CLIENT *);
extern  bool_t shibrpc_get_session_2_svc(shibrpc_get_session_args_2 *, shibrpc_get_session_ret_2 *, struct svc_req *);
extern int shibrpc_prog_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define shibrpc_ping 0
extern  enum clnt_stat shibrpc_ping_2();
extern  bool_t shibrpc_ping_2_svc();
#define shibrpc_new_session 1
extern  enum clnt_stat shibrpc_new_session_2();
extern  bool_t shibrpc_new_session_2_svc();
#define shibrpc_get_session 2
extern  enum clnt_stat shibrpc_get_session_2();
extern  bool_t shibrpc_get_session_2_svc();
extern int shibrpc_prog_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_ShibRpcStatus (XDR *, ShibRpcStatus*);
extern  bool_t xdr_ShibRpcErr (XDR *, ShibRpcErr*);
extern  bool_t xdr_ShibRpcError (XDR *, ShibRpcError*);
extern  bool_t xdr_ShibRpcXML (XDR *, ShibRpcXML*);
extern  bool_t xdr_shibrpc_new_session_args_2 (XDR *, shibrpc_new_session_args_2*);
extern  bool_t xdr_shibrpc_new_session_ret_2 (XDR *, shibrpc_new_session_ret_2*);
extern  bool_t xdr_shibrpc_get_session_args_2 (XDR *, shibrpc_get_session_args_2*);
extern  bool_t xdr_shibrpc_get_session_ret_2 (XDR *, shibrpc_get_session_ret_2*);

#else /* K&R C */
extern bool_t xdr_ShibRpcStatus ();
extern bool_t xdr_ShibRpcErr ();
extern bool_t xdr_ShibRpcError ();
extern bool_t xdr_ShibRpcXML ();
extern bool_t xdr_shibrpc_new_session_args_2 ();
extern bool_t xdr_shibrpc_new_session_ret_2 ();
extern bool_t xdr_shibrpc_get_session_args_2 ();
extern bool_t xdr_shibrpc_get_session_ret_2 ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SHIBRPC_H_RPCGEN */
